# Generated by Django 3.1.7 on 2021-04-01 17:42

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0003_customer'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Customer',
            new_name='ProductCustomer',
        ),
        migrations.RenameField(
            model_name='productcustomer',
            old_name='last_modified',
            new_name='last_Modified',
        ),
        migrations.RenameField(
            model_name='productcustomer',
            old_name='phone_number',
            new_name='phone_Number',
        ),
    ]
