# Generated by Django 3.1.7 on 2021-04-01 18:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0004_auto_20210401_1842'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductWalletHistorie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_debited', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('amount_credited', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('current', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('date_recorded', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-date_recorded',),
            },
        ),
    ]
