# Generated by Django 3.1.7 on 2021-04-03 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20210402_0744'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcustomer',
            name='CAC_Certificate',
            field=models.ImageField(null=True, upload_to='CAC_Xplore/%Y/%m/%d'),
        ),
    ]
