# Generated by Django 3.1.7 on 2021-03-22 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_wallet'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wallet',
            options={'ordering': ('-date_Submitted',)},
        ),
        migrations.RenameField(
            model_name='wallet',
            old_name='amount_paid',
            new_name='amount_Paid',
        ),
        migrations.RenameField(
            model_name='wallet',
            old_name='date_submitted',
            new_name='date_Submitted',
        ),
        migrations.RenameField(
            model_name='wallet',
            old_name='payment_evidence',
            new_name='payment_Evidence',
        ),
        migrations.RenameField(
            model_name='wallet',
            old_name='transaction_date',
            new_name='transaction_Date',
        ),
        migrations.RenameField(
            model_name='wallet',
            old_name='transaction_name',
            new_name='transaction_Name',
        ),
    ]
