# Generated by Django 3.1.7 on 2021-03-23 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20210322_1249'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Wallet',
        ),
    ]
