# Generated by Django 3.1.7 on 2021-04-05 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20210403_2159'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcustomer',
            name='email_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='productcustomer',
            name='CAC_Certificate',
            field=models.ImageField(blank=True, null=True, upload_to='CAC_Certs/%Y/%m/%d'),
        ),
    ]
