# Generated by Django 3.1.7 on 2021-04-10 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20210405_1541'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productwallethistorie',
            old_name='current',
            new_name='current_balance',
        ),
    ]
