# Generated by Django 3.1.7 on 2021-03-28 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20210328_1721'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallethistory',
            name='date_recorded',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
