# Generated by Django 3.1.7 on 2021-04-11 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20210410_2352'),
    ]

    operations = [
        migrations.AddField(
            model_name='productwallethistorie',
            name='last_tran',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
    ]
