# Generated by Django 3.1.7 on 2021-03-28 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_wallethistory_date_recorded'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wallethistory',
            old_name='old_balance',
            new_name='previous_balance',
        ),
    ]
