# Generated by Django 3.1.7 on 2021-03-28 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20210328_1829'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallethistory',
            name='current_balance',
        ),
    ]
