# Generated by Django 3.1.7 on 2021-03-28 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_remove_wallethistory_current_balance'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WalletHistory',
        ),
    ]
