# Generated by Django 3.1.7 on 2021-03-28 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_delete_wallethistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='WalletHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_balance', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('amount_debited', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('amount_credited', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('date_recorded', models.DateTimeField(auto_now_add=True, null=True)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.customer')),
            ],
            options={
                'ordering': ('customer',),
            },
        ),
    ]
