# Generated by Django 3.1.7 on 2021-03-28 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_auto_20210328_1954'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='wallet',
        ),
        migrations.RemoveField(
            model_name='wallethistory',
            name='previous_balance',
        ),
    ]
