# Generated by Django 3.1.7 on 2021-03-28 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_auto_20210328_2054'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallethistory',
            name='current_balance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='wallethistory',
            name='previous_balance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
    ]
