# Generated by Django 3.1.7 on 2021-03-28 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_auto_20210328_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallethistory',
            name='amount_credited',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='wallethistory',
            name='previous_balance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
    ]
