# Generated by Django 3.1.7 on 2021-03-28 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_auto_20210328_2126'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wallethistory',
            options={'ordering': ('-date_recorded',)},
        ),
    ]
