# Generated by Django 3.1.7 on 2021-03-29 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_auto_20210329_0000'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wallethistory',
            old_name='previous_balance',
            new_name='amount_paid',
        ),
    ]
