# Generated by Django 3.1.7 on 2021-03-30 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_customer_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='wallethistory',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
