# Generated by Django 3.1.7 on 2021-03-30 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_auto_20210330_1116'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallethistory',
            name='user',
        ),
    ]
