# Generated by Django 3.1.7 on 2021-03-25 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20210324_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guestproductorder',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
