# Generated by Django 3.1.7 on 2021-03-28 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20210325_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customercredit',
            name='amount_Paid',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True),
        ),
    ]
