# Generated by Django 3.1.7 on 2021-03-30 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20210328_1721'),
    ]

    operations = [
        migrations.AddField(
            model_name='guestproductorder',
            name='phone_number',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='productorder',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='productorder',
            name='phone_number',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
