# Generated by Django 3.1.7 on 2021-03-30 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_auto_20210330_1001'),
    ]

    operations = [
        migrations.AddField(
            model_name='guestproductorder',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
