# Generated by Django 3.1.7 on 2021-03-30 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_guestproductorder_last_modified'),
    ]

    operations = [
        migrations.AddField(
            model_name='productorder',
            name='order_id',
            field=models.CharField(default='9034892247', editable=False, max_length=10, null=True, unique=True),
        ),
    ]
