# Generated by Django 3.1.7 on 2021-03-31 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_productorder_order_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='guestproductorder',
            options={'ordering': ('-date_ordered',)},
        ),
        migrations.AlterModelOptions(
            name='productorder',
            options={'ordering': ('-date_ordered',)},
        ),
        migrations.AlterField(
            model_name='productorder',
            name='order_id',
            field=models.CharField(default='BQ91738034', editable=False, max_length=10, null=True),
        ),
    ]
