# Generated by Django 3.1.7 on 2021-04-01 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_auto_20210331_1947'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guestproductorder',
            name='product',
        ),
        migrations.RemoveField(
            model_name='productorder',
            name='product',
        ),
        migrations.RemoveField(
            model_name='productorder',
            name='user',
        ),
        migrations.DeleteModel(
            name='CustomerCredit',
        ),
        migrations.DeleteModel(
            name='GuestProductOrder',
        ),
        migrations.DeleteModel(
            name='ProductOrder',
        ),
    ]
