# Generated by Django 3.1.7 on 2021-04-01 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_auto_20210401_1744'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
