# Generated by Django 3.1.7 on 2021-03-07 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='user',
        ),
    ]
