# Generated by Django 3.1.7 on 2021-04-02 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_remove_contact_user_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ('-date_Submitted',)},
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='date_submitted',
            new_name='date_Submitted',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='phone_number',
            new_name='phone_Number',
        ),
    ]
