# Generated by Django 3.1.7 on 2021-04-29 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_auto_20210429_0644'),
    ]

    operations = [
        migrations.AddField(
            model_name='advert',
            name='expiry',
            field=models.DateField(null=True),
        ),
    ]
