# Generated by Django 3.1.7 on 2021-05-15 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_advert_expiry'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Advert',
        ),
    ]
