# Generated by Django 3.1.7 on 2021-03-11 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cement', '0003_remove_cement_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cement',
            name='quantity',
        ),
        migrations.AddField(
            model_name='cement',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
