# Generated by Django 3.1.7 on 2021-03-11 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cement', '0005_auto_20210311_1444'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cement',
            options={'ordering': ('type',)},
        ),
    ]
