# Generated by Django 3.1.7 on 2021-03-11 13:25

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cement', '0008_auto_20210311_1512'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrderItem',
            new_name='Order',
        ),
    ]
