# Generated by Django 3.1.7 on 2021-03-11 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cement', '0012_auto_20210311_1534'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cementorder',
            options={'ordering': ('-id',)},
        ),
        migrations.CreateModel(
            name='GuestCementOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=20)),
                ('quantity', models.IntegerField(default=0)),
                ('date_ordered', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Completed', 'Completed'), ('New', 'New'), ('Pending', 'Pending')], default='New', max_length=9, null=True)),
                ('cement', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cement.cement')),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
    ]
