# Generated by Django 3.1.7 on 2021-03-16 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cement', '0013_auto_20210311_1747'),
    ]

    operations = [
        migrations.AddField(
            model_name='cementorder',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='cementorder',
            name='city',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='cementorder',
            name='state',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
