# Generated by Django 3.1.7 on 2021-03-16 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cement', '0014_auto_20210316_0757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cementorder',
            name='address',
            field=models.CharField(blank=True, default='Leave blank to use registered address', max_length=200, null=True),
        ),
    ]
