# Generated by Django 3.1.7 on 2021-03-16 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210311_1609'),
        ('cement', '0016_cementorder_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cementorder',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.customer'),
        ),
    ]
