# Generated by Django 3.1.7 on 2021-03-16 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cement', '0018_remove_cementorder_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='cementorder',
            name='time',
            field=models.CharField(blank=True, default='Schedule a delivery time', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='guestcementorder',
            name='time',
            field=models.CharField(blank=True, default='Schedule a delivery time', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='cementorder',
            name='city',
            field=models.CharField(blank=True, default='Leave blank to use registered city', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='cementorder',
            name='state',
            field=models.CharField(blank=True, default='Leave blank to use registered state', max_length=20, null=True),
        ),
    ]
