# Generated by Django 3.1.7 on 2021-03-16 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cement', '0021_auto_20210316_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cementorder',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='guestcementorder',
            name='address',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='guestcementorder',
            name='time',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
