# Generated by Django 3.1.7 on 2021-03-16 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cement', '0022_auto_20210316_1206'),
    ]

    operations = [
        migrations.AddField(
            model_name='guestcementorder',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
