# Generated by Django 3.1.7 on 2021-03-20 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cement', '0026_remove_cementorder_checkout'),
    ]

    operations = [
        migrations.AddField(
            model_name='cementorder',
            name='checkout',
            field=models.BooleanField(default='False'),
        ),
    ]
