# Generated by Django 3.1.7 on 2021-03-11 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cement', '0028_cementorder_wallet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cementorder',
            name='wallet',
        ),
    ]
