# Generated by Django 3.1.7 on 2021-03-11 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_customer_wallet'),
        ('cement', '0029_remove_cementorder_wallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='cementorder',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.customer'),
        ),
    ]
