# Generated by Django 3.1.7 on 2021-03-22 16:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0006_customer_wallet'),
        ('cement', '0032_cementorder_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cementorder',
            old_name='status',
            new_name='order_status',
        ),
        migrations.RenameField(
            model_name='guestcementorder',
            old_name='status',
            new_name='order_status',
        ),
        migrations.AddField(
            model_name='cementorder',
            name='payment_mode',
            field=models.CharField(choices=[('Pay Instantly', 'Pay Instantly'), ('Pay on Site', 'Pay on Site')], default='Pay Instantly', max_length=14, null=True),
        ),
        migrations.AddField(
            model_name='cementorder',
            name='payment_status',
            field=models.CharField(choices=[('Unconfirmed', 'Unconfirmed'), ('Confirmed', 'Confirmed')], default='Unconfirmed', max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='guestcementorder',
            name='payment_mode',
            field=models.CharField(choices=[('Pay Instantly', 'Pay Instantly'), ('Pay on Site', 'Pay on Site')], default='Pay Instantly', max_length=14, null=True),
        ),
        migrations.AddField(
            model_name='guestcementorder',
            name='payment_status',
            field=models.CharField(choices=[('Unconfirmed', 'Unconfirmed'), ('Confirmed', 'Confirmed')], default='Unconfirmed', max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='cementorder',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.customer'),
        ),
        migrations.AlterField(
            model_name='cementorder',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
