# Generated by Django 3.1.7 on 2021-03-22 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cement', '0037_auto_20210322_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cementorder',
            name='time',
            field=models.DateField(blank=True, null=True),
        ),
    ]
