# Generated by Django 3.1.7 on 2021-03-23 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cement', '0038_auto_20210322_1240'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cementorder',
            old_name='time',
            new_name='schedule_delivery',
        ),
        migrations.RemoveField(
            model_name='guestcementorder',
            name='time',
        ),
        migrations.AddField(
            model_name='guestcementorder',
            name='schedule_delivery',
            field=models.DateField(blank=True, null=True),
        ),
    ]
