# Generated by Django 3.1.7 on 2021-03-23 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cement', '0040_customerwallet'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customerwallet',
            old_name='wallet_customer',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='customerwallet',
            old_name='wallet_user',
            new_name='user',
        ),
    ]
