# Generated by Django 3.1.7 on 2021-03-23 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cement', '0041_auto_20210323_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerwallet',
            name='payment_Evidence',
            field=models.ImageField(null=True, upload_to='payment/%Y/%m/%d'),
        ),
    ]
