# Generated by Django 3.1.7 on 2021-03-23 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cement', '0042_auto_20210323_2102'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cementorder',
            name='customer',
        ),
    ]
