# Generated by Django 3.1.7 on 2021-04-29 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xplorers', '0004_full'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThreeQuarter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(max_length=30, null=True)),
                ('image', models.ImageField(null=True, upload_to='adverts_full/%Y/%m/%d')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('owner',),
            },
        ),
    ]
