# Generated by Django 3.1.7 on 2021-04-29 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xplorers', '0006_auto_20210429_0717'),
    ]

    operations = [
        migrations.CreateModel(
            name='OneQuarter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(max_length=30, null=True)),
                ('image', models.ImageField(null=True, upload_to='adverts_one_quarter/%Y/%m/%d')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('owner',),
            },
        ),
        migrations.AlterField(
            model_name='threequarter',
            name='image',
            field=models.ImageField(null=True, upload_to='adverts_three_quarters/%Y/%m/%d'),
        ),
    ]
