# Generated by Django 3.1.7 on 2021-05-14 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('xplorers', '0008_auto_20210429_2303'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advert_Type', models.CharField(choices=[('One Quarter', 'One Quarter'), ('Three Quarters', 'Three Quarters'), ('Full Width', 'Full Width'), ('Home Page', 'Home Page')], default='One Quarter', max_length=14, null=True)),
                ('image', models.ImageField(null=True, upload_to='subscription/%Y/%m/%d')),
                ('date_Activated', models.DateField(null=True)),
                ('subscription_Ends', models.DateField(null=True)),
                ('xplorer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='xplorers.xplorecustomer')),
            ],
            options={
                'ordering': ('-subscription_Ends',),
            },
        ),
    ]
