# Generated by Django 3.1.7 on 2021-05-14 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('xplorers', '0009_subscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package', models.CharField(choices=[('One Quarter: ₦---', 'One Quarter: ₦---'), ('Three Quarters: ₦---', 'Three Quarters: ₦---'), ('Full Width: ₦---', 'Full Width: ₦---'), ('Home Page: ₦---', 'Home Page: ₦---')], default='One Quarter: ₦---', max_length=20, null=True)),
                ('advert_Image', models.ImageField(null=True, upload_to='advert_image/%Y/%m/%d')),
                ('payment_Evidence', models.ImageField(null=True, upload_to='payment_xplorer/%Y/%m/%d')),
                ('waiver_Code', models.CharField(max_length=10, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('xplorer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='xplorers.xplorecustomer')),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
    ]
