# Generated by Django 3.1.7 on 2021-05-14 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('xplorers', '0011_auto_20210514_1448'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='date_Submitted',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='xplorers.request'),
        ),
    ]
