# Generated by Django 3.1.7 on 2021-05-14 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xplorers', '0012_subscription_date_submitted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='date_Submitted',
            new_name='request_Id',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='advert_Type',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='image',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='xplorer',
        ),
        migrations.AlterField(
            model_name='request',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='date_Activated',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
