# Generated by Django 3.1.7 on 2021-05-14 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('xplorers', '0013_auto_20210514_1521'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='xplorer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='xplorers.xplorecustomer'),
        ),
    ]
