# Generated by Django 3.1.7 on 2021-05-15 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xplorers', '0016_subscription_package'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Full',
        ),
        migrations.DeleteModel(
            name='OneQuarter',
        ),
        migrations.DeleteModel(
            name='ThreeQuarter',
        ),
    ]
