# Generated by Django 3.1.7 on 2021-05-30 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userorderstatus',
            name='order_Status',
            field=models.CharField(choices=[('Delivered', 'Delivered'), ('Out for Delivery', 'Out for Delivery')], default='Out for Delivery', max_length=16, null=True),
        ),
    ]
