# Generated by Django 3.1.7 on 2021-05-30 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_userorderstatus_order_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userorderstatus',
            old_name='order_Status',
            new_name='status',
        ),
    ]
