# Generated by Django 3.1.7 on 2021-05-21 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20210421_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userorder',
            name='order_Id',
            field=models.CharField(default=2021, max_length=10, null=True),
        ),
    ]
