# Generated by Django 3.1.7 on 2021-05-21 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_userorderstatus'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userorderstatus',
            options={'ordering': ('-created',), 'verbose_name': 'User Order Status', 'verbose_name_plural': 'User Order Statuses'},
        ),
        migrations.AddField(
            model_name='visitororder',
            name='delivery_Status',
            field=models.CharField(default='New', max_length=3, null=True),
        ),
    ]
