# Generated by Django 3.1.7 on 2021-05-21 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_auto_20210521_1324'),
    ]

    operations = [
        migrations.AddField(
            model_name='userorder',
            name='delivery_Status',
            field=models.CharField(default='New', max_length=3, null=True),
        ),
    ]
