# Generated by Django 3.1.7 on 2021-04-02 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guestorder',
            name='order_Id',
            field=models.CharField(default='BQ55912880', editable=False, max_length=10, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='registeredorder',
            name='order_Id',
            field=models.CharField(default='BQ38915866', editable=False, max_length=10, null=True, unique=True),
        ),
    ]
