# Generated by Django 3.1.7 on 2021-04-02 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20210402_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guestorder',
            name='order_Id',
            field=models.CharField(default='BQ33886607', editable=False, max_length=10, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='registeredorder',
            name='order_Id',
            field=models.CharField(default='BQ53068621', editable=False, max_length=10, null=True, unique=True),
        ),
    ]
