# Generated by Django 3.1.7 on 2021-04-02 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20210402_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userorder',
            name='order_Id',
            field=models.CharField(default='BQ94519786', editable=False, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='visitororder',
            name='order_Id',
            field=models.CharField(default='BQ66566654', editable=False, max_length=10, null=True),
        ),
    ]
