# Generated by Django 3.1.7 on 2021-04-02 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_auto_20210402_0652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userorder',
            name='order_Id',
            field=models.CharField(default=2021, editable=False, max_length=10, null=True),
        ),
    ]
