# Generated by Django 3.1.7 on 2021-04-10 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_auto_20210403_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcredit',
            name='transaction_Date',
            field=models.DateField(null=True),
        ),
    ]
