# Generated by Django 3.1.7 on 2021-04-20 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_userinfo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserInfo',
        ),
    ]
