# Generated by Django 3.1.7 on 2021-04-21 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0022_auto_20210421_0946'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('type',), 'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='type',
        ),
    ]
