# Generated by Django 3.1.7 on 2021-04-21 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0025_orderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userorder',
            name='product',
        ),
        migrations.RemoveField(
            model_name='userorder',
            name='user',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
        migrations.DeleteModel(
            name='UserOrder',
        ),
    ]
