# Generated by Django 3.1.7 on 2021-04-21 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0026_auto_20210421_1434'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VisitorOrder',
        ),
    ]
