# Generated by Django 3.1.7 on 2021-04-28 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0027_delete_visitororder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='available',
        ),
        migrations.RemoveField(
            model_name='product',
            name='stock',
        ),
    ]
