# Generated by Django 3.1.7 on 2021-08-31 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0028_auto_20210428_2352'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('-date',)},
        ),
    ]
